web/core/__init__.py
#!usr/bin/env python
# -*- coding:utf-8 _*-
"""
# author: fyh
# time: 2024/5/21
"""

# 导入蓝图
from flask import Blueprint

cnnvd_blue = Blueprint('cnnvd', __name__, url_prefix="/cnnvd", template_folder="templates", static_folder="static")

from . import views

web/core/views.py
import pandas as pd
from io import BytesIO
from . import cnnvd_blue
from flask import Flask, request, jsonify
from db.manager import SqlManager
import os
import datetime
from log.log import CustomLogger

logger = CustomLogger(__name__).get_logger()

DOWNLOAD_FOLDER = os.path.join(os.path.abspath(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), 'download/excel')

@cnnvd_blue.route("/generate", methods=['GET'])
async def generate_excel():
    days = request.args.get("days", default="", type=str)
    create_time = None
    file_name = "all"
    if days:
        file_name = f"before-{days}"
        create_time = datetime.datetime.combine(datetime.datetime.now() - datetime.timedelta(days=int(days)), datetime.time.min)
   
    try:
        dbm = await SqlManager()

        # 获取数据总数
        total_records = await dbm.get_connvd_count(create_time)
        logger.info(f"Excel文件正在生成:{total_records}")
        batch_size = 10000  # 每批处理的记录数
        
        # 文件路径
        excel_file_path = os.path.join(DOWNLOAD_FOLDER, f'cnnvd-nvd-{file_name}.xlsx')
        sheet_name = 'Sheet1'
        start_row = 0

        with pd.ExcelWriter(excel_file_path, engine='openpyxl', mode='w') as writer:
            header_written = False
            for offset in range(0, total_records, batch_size):
                data = await dbm.get_connvd_offset(limit=batch_size, offset_val=offset, create_time=create_time)
                df = pd.DataFrame(data)
                df.to_excel(writer, sheet_name=sheet_name, startrow=start_row, index=False, header=not header_written)
                start_row += len(df)
                header_written = True

        logger.info("Excel文件生成成功")
        return jsonify({"message": "Excel file generated successfully"}), 200

    except Exception as e:
        logger.error(e)
        return jsonify({"message": "Excel file generation failed!"}), 400

    finally:
        await dbm.close()

web/templates/folder.html
<!DOCTYPE html>
<html>
<head>
    <title>Folder {{ folder }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f8f9fa;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        li {
            margin-bottom: 10px;
        }
        a {
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        .back-link {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>文件夹 {{ folder }}</h1>
    <p class="back-link"><a href="{{ url_for('index') }}">返回上级目录</a></p>
    <h2>Files:</h2>
    <ul>
        {% for file in files %}
        <li><a href="{{ url_for('download_file', filename=folder + '/' + file) }}" download>{{ file }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

web/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Download Folder</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f8f9fa;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        li {
            margin-bottom: 10px;
        }
        a {
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        .generate-button {
            display: inline-block;
            margin-bottom: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #ffffff;
            text-decoration: none;
            border-radius: 4px;
        }
        .generate-button:hover {
            background-color: #0056b3;
        }
    </style>
    <script>
        function disableButton() {
            var button = document.getElementById('generateButton');
            button.disabled = true;
            button.innerText = '正在生成...';
        }

        function enableButton() {
            var button = document.getElementById('generateButton');
            button.disabled = false;
            button.innerText = '生成 Excel';
        }

        document.addEventListener("DOMContentLoaded", function() {
            var form = document.getElementById("generateForm");
            form.onsubmit = async function(event) {
                event.preventDefault();
                disableButton();

                var days = document.getElementById("days").value;
                var url = form.action + "?days=" + days;

                try {
                    let response = await fetch(url);
                    let result = await response.json();
                    if (response.ok) {
                        alert(result.message);
                    } else {
                        alert("Error: " + result.message);
                    }
                } catch (error) {
                    alert("An error occurred: " + error.message);
                } finally {
                    enableButton();
                }
            };
        });
    </script>
</head>
<body>
    <h1>漏洞知识库</h1>
    <form id="generateForm" method="get" action="{{ url_for('cnnvd.generate_excel') }}">
        <label for="days">选择时间范围:</label>
        <select id="days" name="days">
            <option value="">全部</option>
            <option value="7">一周前</option>
            <option value="30">30天前</option>
            <option value="60">60天前</option>
            <option value="90">90天前</option>
        </select>
        <button type="submit" class="generate-button" id="generateButton">生成 Excel</button>
    </form>

    <h2>漏洞信息文件:</h2>
    <ul>
        {% for folder in folders %}
        <li><a href="{{ url_for('open_folder', folder=folder) }}">{{ folder }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>